CREATE TABLE IF NOT EXISTS "USER"(
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255),
    google_access_token TEXT,
    google_refresh_token TEXT,
    google_token_expires_at TIMESTAMP
);


CREATE TABLE IF NOT EXISTS "AGENT_THREAD"(
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255),
    steps JSONB DEFAULT '[]'::jsonb,
    watcheTool VARCHAR(255) DEFAULT '[]',
    updateTool VARCHAR(255) DEFAULT '[]',
    user_id VARCHAR(255) NOT NULL REFERENCES "USER"(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DO $$ BEGIN
    CREATE TYPE role_enum AS ENUM ('user', 'assistant');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS "MESSAGE"(
    id VARCHAR(255) PRIMARY KEY,
    thread_id VARCHAR(255) NOT NULL REFERENCES "AGENT_THREAD"(id),
    message JSONB,
    role role_enum NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "USER" ADD COLUMN IF NOT EXISTS google_access_token TEXT;
ALTER TABLE "USER" ADD COLUMN IF NOT EXISTS google_refresh_token TEXT;
ALTER TABLE "USER" ADD COLUMN IF NOT EXISTS google_token_expires_at TIMESTAMP;
ALTER TABLE "AGENT_THREAD" DROP COLUMN IF EXISTS status;
ALTER TABLE "AGENT_THREAD" ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE "AGENT_THREAD" ADD COLUMN IF NOT EXISTS steps JSONB DEFAULT '[]';
ALTER TABLE "AGENT_THREAD" ADD COLUMN IF NOT EXISTS watcheTool VARCHAR(255) DEFAULT '[]';
ALTER TABLE "AGENT_THREAD" ADD COLUMN IF NOT EXISTS updateTool VARCHAR(255) DEFAULT '[]';
ALTER TABLE "AGENT_THREAD" DROP COLUMN IF EXISTS message;